Feature/echo server
world-famous-webserv/webserv pull request #6
Opened 2023-09-21 14:18 UTC by joseoungmin

> socket을 사용한 에코서버 업로드

2023-09-21 14:42 UTC, juwkim commented on libs/listener/Listener.hpp
> +#include <stdio.h>
cstdio

2023-09-21 14:42 UTC, juwkim commented on libs/listener/Listener.hpp
> +#include <string.h>
cstring

2023-09-21 14:42 UTC, juwkim commented on libs/listener/Listener.hpp
> +		int		m_serverSocket;
mServerSocket

2023-09-21 14:42 UTC, juwkim commented on libs/listener/Listener.hpp
> +		string	m_address;
mAddress

2023-09-21 14:42 UTC, juwkim commented on libs/listener/Listener.hpp
> +		int		m_port;
mPort

2023-09-21 14:42 UTC, juwkim commented on libs/listener/Listener.hpp
> +		bool	m_listening;
mListening

2023-09-21 14:42 UTC, juwkim commented on libs/listener/server.cpp
> +#include <stdio.h>
cstdio

2023-09-21 14:42 UTC, juwkim commented on libs/listener/server.cpp
> +	if (acceptor->start() == 0) {
early return

2023-09-21 14:43 UTC, iijung requested changes
확인하고 수정 부탁드립니다.

2023-09-21 14:43 UTC, iijung commented on libs/listener/.vscode/c_cpp_properties.json
vscode 설정이 잘못 추가 된 것 같습니다.  제거해주세요.

2023-09-21 14:43 UTC, iijung commented on libs/listener/.vscode/settings.json
vscode 설정이 잘못 추가 된 것 같습니다. 제거해주세요.

2023-09-21 14:43 UTC, iijung commented on libs/listener/Listener.cpp
> +	//setsockopt(m_serverSocket, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof optval);
setsockopt 써보는 거 좋은 것 같습니다! 주석 해제하고 되는 코드로 만들어주세요

2023-09-21 14:43 UTC, iijung commented on libs/listener/Listener.cpp
> +		perror("bind() failed");
허용 함수가 아닌 것 같습니다.

2023-09-21 14:43 UTC, iijung commented on libs/listener/Listener.cpp
> +		perror("listen() failed");
허용 함수가 아닌 것 같습니다.

2023-09-21 14:43 UTC, iijung commented on libs/listener/Listener.hpp
> +#include "TcpStream.hpp"
TCPStream 헤더를 include 하는데 중복 헤더가 많은 것 같습니다. 
그리고 string.h 는 cstring 같은 c++ 헤더가 존재합니다.

2023-09-21 14:43 UTC, iijung commented on libs/listener/Listener.hpp
> +		Listener(int port, const char* address="");
이거 저번에 같이 수정한 내용 아닌가요? cppcheck에서 걸렸던 것 같은데 프로토타입에서 default 변수를 지정하기보다는 구현부에서 지정하는게 좋을 것 같습니다.

2023-09-21 14:43 UTC, iijung commented on libs/listener/TcpStream.cpp
> +	inet_ntop(PF_INET, reinterpret_cast<const struct in_addr*>(&address->sin_addr.s_addr), ip, sizeof(ip)-1);
허용함수 X

2023-09-21 14:43 UTC, iijung commented on libs/listener/Listener.hpp
> +#ifndef Listener_HPP
`#ifndef Listener_HPP` --> `#ifndef LISTENER_HPP`

2023-09-21 14:43 UTC, iijung commented on libs/listener/client.cpp
테스트 프로그램에 대한 것은 $ROOT/test 디렉토리에 별도의 디렉토리로 Makefile 을 만들어서 올려주시면 더 좋을 것 같습니다.

2023-09-21 14:43 UTC, iijung commented on libs/listener/server.cpp
테스트 프로그램에 대한 것은 $ROOT/test 디렉토리에 별도의 디렉토리로 Makefile 을 만들어서 올려주시면 더 좋을 것 같습니다.

2023-09-21 14:43 UTC, iijung commented on libs/listener/tcpstream.hpp
파일명이 전부 소문자에요

2023-09-21 14:43 UTC, iijung commented on libs/listener/tcpstream.hpp
> +#define TCPSTREAM_HPP
TCP_STREAM_HPP

2023-09-21 14:43 UTC, iijung commented on libs/listener/tcpstream.hpp
> +#include <sys/select.h>
TcpStream 클래스 내부에서는 select 관련 함수를 안 쓰는 것 같아요

2023-09-21 14:43 UTC, iijung commented on libs/listener/tcpstream.hpp
> +		int			get_sd() { return m_clientSocket; }
`inline int getSd(void)`
`int TcpStream::getSd(void) { return m_clientSocket; }`

2023-09-26 04:03 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +#include <stdio.h>
delete: <stdio.h>

2023-09-26 04:03 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +#include <string.h>
delete: <string.h>

2023-09-26 04:08 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +		int		m_serverSocket;
update: "m_serverSocket" -> "mServerSocket"

2023-09-26 04:08 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +		string	m_address;
update: "m_address" -> "mAddress"

2023-09-26 04:14 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +		int		m_port;
update: "m_port" -> "mPort"

2023-09-26 04:16 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +		bool	m_listening;
update: "m_listening" -> "mListening"

2023-09-26 04:17 UTC, joseoungmin commented on libs/listener/server.cpp
> +#include <stdio.h>
delete: "<stdio.h>"

2023-09-26 04:25 UTC, joseoungmin commented on libs/listener/tcpstream.hpp
> +#include <sys/select.h>
delete: "<sys/types.h>", "<sys/socket.h>", "sys/select.h"

2023-09-26 04:25 UTC, joseoungmin commented on libs/listener/tcpstream.hpp
> +#define TCPSTREAM_HPP
update: "TCPSTREAM_HPP" -> "TCP_STREAM_HPP"

2023-09-26 04:34 UTC, joseoungmin commented on libs/listener/tcpstream.hpp
> +		int			get_sd() { return m_clientSocket; }
delete: "int getSd(void)"

2023-09-26 05:33 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +#ifndef Listener_HPP
update: "ifndef Listener_HPP" --> "ifndef LISTENER_HPP"

2023-09-26 05:36 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +#include "TcpStream.hpp"
update: 중복헤더 삭제, c헤더 삭제

2023-09-26 06:12 UTC, joseoungmin commented on libs/listener/Listener.hpp
> +		Listener(int port, const char* address="");
update: add "Listener(int port);"
// 3W 에러 체크에서 걸려서 address가 없는 생성자를 추가했습니다.

2023-09-29 14:30 UTC, joseoungmin commented on libs/listener/tcpstream.hpp
수정했습니다

2023-09-29 14:30 UTC, joseoungmin commented on libs/listener/Listener.cpp
> +		perror("listen() failed");
변경했습니다

2023-09-29 14:30 UTC, joseoungmin commented on libs/listener/Listener.cpp
> +		perror("bind() failed");
변경완료

2023-10-20 07:23 UTC, closed without merging

2023-10-20 08:17 UTC, iijung commented
아래의 리퀘스트와 동일하므로 해당 리퀘스트는 닫습니다. 
- #7