Feature/echo server
world-famous-webserv/webserv pull request #7
Opened 2023-10-19 11:25 UTC by joseoungmin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-10-20 08:12 UTC, iijung requested changes
**1. commit을 하기 전 반영되는 파일과 아닌 파일을 확실히 구분하시면 좋을 것 같습니다.** 
`git add .; git commit -m "asdf"`를 하는 건 좋은 습관이 아니라고 생각합니다. 불필요한 파일이 커밋 이력에 섞이면 리뷰 및 히스토리 분석이 어렵습니다.

**2. git message convention을 검색해보고 해당 태그를 사용해주시면 더 좋을 것 같습니다.** 
예를 들어서 update: ... 보다는 style(포맷 변경), docs(문서 추가), chore(빌드환경 등), fix(버그 수정), feat(기능 추가),  refacotr(기능 개선) 등 해당 커밋의 `목표`와 어떤 `이유`로 파일이 업데이트 됐는지 작성해주시면 좋을 것 같습니다

**3. 하루 작업 단위가 아닌 (2)의 목표에 따른 작업 단위로 커밋 부탁드립니다. **
`git comit --amend` 같은 명령어로 최신 커밋을 수정하거나 임시 저장이 필요할 때는 별도의 temp 브랜치를 만들어서 저장하시고 추후에 결과물을 합치는 방법도 있습니다.

2023-10-20 08:12 UTC, iijung commented on docs/README.md
불필요한 파일이 섞인 것 같습니다. commit 전에 git status로 커밋 목록 확인해주세요.

2023-10-20 08:12 UTC, iijung commented on libs/listener/.vscode/c_cpp_properties.json
불필요한 파일이 같이 반영됐습니다. commit 전 확인 부탁드립니다.

2023-10-20 08:12 UTC, iijung commented on libs/listener/.gitignore
.gitignore 파일을 생성하기 전에 git add 를 먼저 하셔서 .vscode 파일들이 같이 기록된 것 같습니다

2023-10-20 08:12 UTC, iijung commented on libs/listener/.vscode/settings.json
불필요한 파일이 섞인 것 같습니다. commit 전에 git status로 커밋 목록 확인해주세요.

2023-10-20 08:12 UTC, iijung commented on libs/listener/Asocket.hpp
> +
#pragma once는 표준이 아니며 동작하지 않을 가능성이 있으므로 ifndef 헤더 가드가 필요합니다

2023-10-20 08:12 UTC, iijung commented on libs/listener/Asocket.hpp
> +		ASocket();
기본 port를 명시하지 않는 default 생성자를 public으로 쓰는 경우가 있나요?

2023-10-20 08:12 UTC, iijung commented on libs/listener/Asocket.hpp
> +
추상 클래스는 순수 가상함수를 하나 이상 포함된 클래스를 의미합니다. 

Abstract Socket 이니까 순수 가상함수가 필요할 것 같습니다.

2023-10-20 08:12 UTC, iijung commented on libs/listener/ClientSocket.cpp
> +	std::cout << "ClientSocket.cpp = Client->Port: " << mPort << "\n";
아무 동작도 안 하는 ASocket을 부모 클래스의 생성자로 호출해서 중복 코드를 늘리기 보다는 ASocket(sd, address)를 호출해서 생성자를 깔끔하게 구현하는게 더 좋을 것 같습니다.

```cpp
ClientSocket::ClientSocket(const int sd,  struct sockaddr_in * address)
	: ASocket(sd, address)
{
}
```

2023-10-20 08:12 UTC, iijung commented on libs/listener/ClientSocket.hpp
> +#include "ASocket.hpp"
#pragma once는 표준이 아니며 동작하지 않을 가능성이 있으므로 ifndef 헤더 가드가 필요합니다

2023-10-20 08:12 UTC, iijung commented on libs/listener/ServerSocket.cpp
> +
아무런 초기화도 수행하지 않는 생성자가 필요한가요?

2023-10-20 08:12 UTC, iijung commented on libs/listener/ServerSocket.cpp
> +	memset(&address, 0, sizeof(address));
허용함수가 아닌 걸로 알고 있습니다. 큰 문제는 없지만 std::memset으로 호출하시거나 ={}을 쓰는게 어떠신가요?

2023-10-20 08:12 UTC, iijung commented on libs/listener/ServerSocket.cpp
> +			line[len] = '\0';
sizeof(line) 만큼 가져오면 LINE_BUFFER_SIZE 만큼의 길이인 `abcdef` 라는 문자열을 가져왔을 때 `abcde개행` 으로 `f`가 덮어씌워질텐데 데이터 누락이 발생하지 않을까요?

2023-10-20 08:12 UTC, iijung commented on libs/listener/ServerSocket.hpp
> +
#pragma once는 표준이 아니며 동작하지 않을 가능성이 있으므로 ifndef 헤더 가드가 필요합니다

2023-10-20 08:12 UTC, iijung commented on libs/listener/ServerSocket.hpp
> +		ServerSocket();
client와 동일한 문제

2023-10-20 08:12 UTC, iijung commented on src/main.cpp
socket 테스트를 위한 main 문은 test/socket 디렉터리를 만들어서 별도의 Makefile을 구현하는게 더 좋을 것 같습니다.
그리고 허용함수가 아닌 c 라이브러리에서 제공하는 atoi 보다는 std::atoi를 사용하는게 어떨까 싶습니다.

2023-10-31 19:56 UTC, juwkim commented on libs/listener/ServerSocket.cpp
> +	memset(&address, 0, sizeof(address));
https://en.cppreference.com/w/cpp/language/aggregate_initialization
이거 참고해보세요~

2023-10-31 19:59 UTC, juwkim commented on libs/listener/ServerSocket.hpp
> +
다중 포함 최적화 (#pragma once, #ifndef 등)의 방법이 있어요.
전자는 표준이 아니지만, but 우리가 쓰는 대부분의 컴파일러가 구현합니다.
후자는 표준이므로, 모든 컴파일러는 반드시 구현합니다.

2023-10-31 20:08 UTC, juwkim requested changes

2023-10-31 20:08 UTC, juwkim commented on libs/listener/ASocket.cpp
const를 붙일 수 있는 모든 곳에 붙이는 건 어떨까요?
23번째 줄의 생성자에서, address의 값을 변경하지 않으므로
const char* address 보다는 const char *const address가 보다 더 안전한 코드라고 생각됩니다.

2023-10-31 20:08 UTC, juwkim commented on libs/listener/ClientSocket.cpp
> +	std::cout << "ClientSocket.cpp = Client->Port: " << mPort << "\n";
address를 변경하지 않고 있으므로 const를 활용해보는 건 어떨까요?

2023-11-05 05:28 UTC, joseoungmin commented on libs/listener/ServerSocket.cpp
> +			line[len] = '\0';
오버플로우의 가능성이 있어서 수정하였습니다

2023-11-05 05:28 UTC, joseoungmin commented on libs/listener/ServerSocket.hpp
> +
모든 컴파일러가 동작할 수 있도록 #ifndef 방식으로 수정하였습니다

2023-11-29 01:14 UTC, closed without merging