Config
world-famous-webserv/webserv pull request #9
Opened 2023-11-02 16:56 UTC by juwkim

2023-11-02 17:17 UTC, iijung commented
지금 자려던 참이라 모바일로 간략하게만 확인 했습니다. 피곤해서 파일 줄 단위 리뷰는 자고 일어나서 맨 정신으로 테스트 하면서 다시 남길게요.

전체적으로 이력이 깔끔한데 동작이 안되는 코드만 커밋하신 부분이 종종 보입니다.

샘플코드 최신 커밋에서 수정해주셨지만 가능하다면 비슷한 작업 끼리 미리 커밋을 묶어두시면 더 좋았을 것 같아요!

그리고 make -s 옵션을 사용하면 사일런트 모드로 동작합니다. @를 사용하면 나중에 make 결과를 파일로 뽑기 힘들어서 어디서 오류났는지 잡기 힘들거에요

그리고 CPPFLAGS에 -I 옵션을 지정해두면 헤더 위치을 찾아갈 수 있어서 config.h를 바로 불러올 수 있습니다. 이력 확인해보니 처음에는 이걸 원하셨던 것 같아서 이야기 들려요.

2023-11-03 07:32 UTC, iijung requested changes
전체적으로 괜찮은데 c++11 확인해주세요 ㅠㅠ ...

2023-11-03 07:32 UTC, iijung commented on libs/config/Makefile
> +LDLIBS		+= -lsample -lconfig
sample 라이브러리를 같이 링킹할 필요는 없을 것 같습니다.

2023-11-03 07:32 UTC, iijung commented on test/config/main.cpp
> +#include "../../libs/config/config.hpp"
Makefile의 CPPFLAGS 참고해주세요. -I 옵션을 통해 경로를 지정해주면 config.hpp로 사용할 수 있습니다.

2023-11-03 07:32 UTC, iijung commented on libs/config/config.hpp
> +        std::unordered_map<std::string, value_type> mDict;
typedef value_type 지정한 부분이 좋았는데 여기서도 사용하는 건 어떨까요?

2023-11-03 07:32 UTC, iijung commented on test/config/Makefile
> +# **************************************************************************** #
norminette 없으니까 42헤더 없이 가요!

2023-11-03 07:32 UTC, iijung commented on test/config/Makefile
> +CPPFLAGS        =	-I./
`-I../../libs/config` 설정 해보시는 거 추천드립니다

2023-11-03 07:32 UTC, iijung commented on test/config/Makefile
> +CXXFLAGS        =	-Wall -Wextra -Werror -pipe -std=c++98
-pipe 옵션은 처음보는데 뭔가요?

2023-11-03 07:32 UTC, iijung commented on libs/config/config.hpp
> +#include <unordered_map>
c++11에서 지원되므로 수정 필요!

2023-11-03 07:32 UTC, iijung commented on libs/config/config.cpp
> +    std::ifstream in(file, std::ios_base::in);
여기서 c++11 관련 오류가 발생했는데 확인 부탁드립니다.

2023-11-03 07:32 UTC, iijung commented on libs/config/config.hpp
> +#pragma once
헤더 가드 작성해주세요

2023-11-04 09:34 UTC, iijung reviewed
이건 노션에 공유드린 내용이고 README.md는 프로젝트를 설명하기 위한 파일이니 여기에 복붙하는 것 보다는 wiki에 추가하고 해당 링크를 연결시키는게 더 좋지 않을까요? 이 내용은 revert 하는게 좋을 것 같아요

2023-11-04 10:07 UTC, iijung commented on libs/config/config.hpp
> +#pragma once
asdf

2023-11-04 10:09 UTC, juwkim commented
> 이건 노션에 공유드린 내용이고 README.md는 프로젝트를 설명하기 위한 파일이니 여기에 복붙하는 것 보다는 wiki에 추가하고 해당 링크를 연결시키는게 더 좋지 않을까요? 이 내용은 revert 하는게 좋을 것 같아요

네 알겠습니다~

2023-11-04 10:14 UTC, juwkim commented on libs/config/config.hpp
> +#pragma once
헤더 가드 작성했습니다~

2023-11-04 10:14 UTC, juwkim commented on libs/config/config.cpp
> +    std::ifstream in(file, std::ios_base::in);
https://en.cppreference.com/w/cpp/io/basic_ifstream/basic_ifstream
c++ 11부터 std::ifstream "const std::string& filename"타입의 인자를 첫번째로 받는 생성자가 지원이 되었다고 합니다.
c++ 11전에는 "const char* filename" 타입의 인자를 첫번째로 주면 된다네요.
그래서 .c_str를 추가했습니다.

2023-11-04 10:14 UTC, juwkim commented on libs/config/Makefile
> +LDLIBS		+= -lsample -lconfig
sample 파일 링킹하는 코드 삭제했습니다.

2023-11-04 10:14 UTC, juwkim commented on libs/config/config.hpp
> +#include <unordered_map>
수정했습니다~

2023-11-04 10:14 UTC, juwkim commented on test/config/Makefile
> +# **************************************************************************** #
네! 42헤더 삭제하겠습니다.

2023-11-04 10:14 UTC, juwkim commented on test/config/Makefile
> +CXXFLAGS        =	-Wall -Wextra -Werror -pipe -std=c++98
https://wiki.gentoo.org/wiki/GCC_optimization/ko#-pipe
gcc에서 컴파일 각 단계의 프로그램(전처리기, 컴파일러, 어셈블러, 링커) 사이 정보를 전달할때 파이프를 통해 전달합니다.
-pipe 옵션이 없으면, 이전 프로그램에서 다음 프로그램에서 각 단계의 결과물을 전달할 때 임시파일을 생성해서 전달합니다.
하지만 pipe 옵션을 추가하면, 파이프를 통해 전달하기 때문에 컴파일 속도가 빨라집니다. 파일을 쓰기 위해 디스크를 갔다 올 필요없이 메모리만 갔다오면 충분하기 때문입니다.
하지만 메모리가 충분하지 않은 환경에서 사용하면 컴파일이 실패할 가능성도 있어요.

2023-11-04 10:14 UTC, juwkim commented on test/config/Makefile
> +CPPFLAGS        =	-I./
수정했습니다.

2023-11-04 10:14 UTC, juwkim commented on test/config/main.cpp
> +#include "../../libs/config/config.hpp"
수정했습니다.

2023-11-04 10:14 UTC, juwkim commented on libs/config/config.hpp
> +        std::unordered_map<std::string, value_type> mDict;
typedef 적극적으로 사용하였습니다.

2023-11-04 10:25 UTC, iijung approved these changes

2023-11-04 14:15 UTC, merged